---
# https://docs.ansible.com/ansible/latest/modules/gce_module.html
- name: GCE Running Ricopili Serial
  hosts: localhost
  vars:
    machine_type: n1-standard-1
    image: ricopili-serial-21-01-2019
    zone: us-central1-a
    service_account_email: ricopili-ansible@ripkelab2019.iam.gserviceaccount.com
    credentials_file: /Users/vasa/.gcloud/keys/ricopili-ansible.json
    project_id: ripkelab2019
  tasks:
    - name: create ricopili-golem
      gce:
        instance_names: test05
        zone: "{{ zone }}"
        machine_type: "{{ machine_type }}"
        image: "{{ image }}"
        state: present
        service_account_email: "{{ service_account_email }}"
        credentials_file: "{{ credentials_file }}"
        project_id: "{{ project_id }}"
        metadata : '{ "startup-script" : "apt-get update" }'
      register: gce

    - name: save host data
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: gce_instances_ips
      with_items: "{{ gce.instance_data }}"

    - name: wait for SSH for instances
      wait_for:
        delay: 1
        host: "{{ item.public_ip }}"
        port: 22
        state: started
        timeout: 30
      with_items: "{{ gce.instance_data }}"

    - name: work work work
      delegate_to:  "{{ groups.gce_instances_ips[0] }}"
      remote_user: vassily
      become_method: su
      become: yes
      shell: date
      tags:
        - work

    - name: delete ricopili-golem
      gce:
        service_account_email: "{{ service_account_email }}"
        credentials_file: "{{ credentials_file }}"
        project_id: "{{ project_id }}"
        instance_names: test05
        zone: "{{ zone }}"
        state: absent
      tags:
        - delete